<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2019-03-22T23:21:18+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'UTC',
];
