<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2019-04-25T15:11:47+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.latest_version
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'locale' => 'es_PY',
    'version_installed' => '8.5.0',
    'version_db_installed' => '20190301133300',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1553296877,
        'do_page_reindex_check' => false,
        'latest_version' => '8.5.0',
    ],
    'accessibility' => [
        'toolbar_titles' => true,
        'toolbar_tooltips' => true,
        'toolbar_large_font' => false,
        'display_help_system' => false,
    ],
    'file_manager' => [
        'images' => [
            'preview_image_size' => 'full',
            'preview_image_popover' => true,
        ],
    ],
    'cache' => [
        'clear' => [
            'thumbnails' => false,
        ],
    ],
    'api' => [
        'enabled' => true,
        'grant_types' => [
            'client_credentials' => false,
            'authorization_code' => false,
            'password_credentials' => false,
        ],
    ],
    'i18n' => [
        'choose_language_login' => null,
    ],
];
