<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2019-03-23T03:44:12+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.editor.ckeditor4.plugins.selected
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Edgar Cabral | Asesor creativo',
            'misc' => [
                'favicon_fid' => 1,
                'iphone_home_screen_thumbnail_fid' => 3,
                'modern_tile_thumbnail_fid' => 4,
                'modern_tile_thumbnail_bgcolor' => 'rgb(46, 149, 180)',
                'browser_toolbar_color' => 'rgb(46, 149, 180)',
            ],
            'editor' => [
                'concrete' => [
                    'enable_filemanager' => true,
                    'enable_sitemap' => true,
                ],
                'ckeditor4' => [
                    'plugins' => [
                        'selected' => [
                            'concrete5filemanager',
                            'concrete5inline',
                            'concrete5uploadimage',
                            'dialogadvtab',
                            'divarea',
                            'floatingspace',
                            'normalizeonchange',
                            'resize',
                            'toolbar',
                            'wysiwygarea',
                            'autogrow',
                            'a11yhelp',
                            'blockquote',
                            'colorbutton',
                            'colordialog',
                            'concrete5link',
                            'contextmenu',
                            'undo',
                            'elementspath',
                            'emoji',
                            'enterkey',
                            'entities',
                            'liststyle',
                            'stylescombo',
                            'basicstyles',
                            'concrete5styles',
                            'ckawesome',
                            'font',
                            'format',
                            'tabletools',
                            'htmlwriter',
                            'image',
                            'image2',
                            'indentblock',
                            'indentlist',
                            'smiley',
                            'justify',
                            'horizontalrule',
                            'list',
                            'magicline',
                            'showblocks',
                            'showborders',
                            'newpage',
                            'pastefromword',
                            'removeformat',
                            'tableresize',
                            'sourcedialog',
                            'sourcearea',
                            'specialchar',
                            'tab',
                            'table',
                            'tableselection',
                        ],
                    ],
                ],
            ],
        ],
    ],
];
